generator: admingenerator.generator.doctrine
params:
    model: Parabol\AdminCoreBundle\Entity\Code
    namespace_prefix: Parabol
    concurrency_lock: ~
    bundle_name: AdminCoreBundle
    pk_requirement: ~
    fields: 
        url:
            label: URL
        inherited:
            label: Dziedziczony
        head:
            addFormOptions:
                attr:
                    style: 'height: 500px'
        body:
            addFormOptions:
                attr:
                    style: 'height: 500px'
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Lista kod√≥w head/body
            display: [url, inherited, updatedAt]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: Nowy kod head/body
            display: [url, inherited, head, body]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Edycja kodu head/body \"%object%\"|{ %object%: Code.url }|"
            display: [url, inherited, head, body]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Kodu head/body \"%object%\"|{ %object%: Code.url }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
