parabol_admin_core_code:
    resource: "@AppAdminCoreBundle/Controller/Code/"
    type:     admingenerator
    prefix:   /codes

parabol_admin_core_page:
    resource: "@AppAdminCoreBundle/Controller/Page/"
    type:     admingenerator
    prefix:   /pages

parabol_admin_core_post:
    resource: "@AppAdminCoreBundle/Controller/Post/"
    type:     admingenerator
    prefix:   /posts

parabol_admin_core_seo:
    resource: "@AppAdminCoreBundle/Controller/Seo/"
    type:     admingenerator
    prefix:   /seo

# parabol_admin_action:
#     path:   /action/{action}    
#     defaults: { _controller: ParabolAdminCoreBundle:Admin:action }

# parabol_admin_core_custom_file:
#     path:   /custom-file/{type}/{filename}    
#     defaults: { _controller: ParabolAdminCoreBundle:Admin:customFile }

# parabol_admin_core_check_url:
#     path:   /check-url
#     defaults: { _controller: ParabolAdminCoreBundle:Admin:checkUrl }

parabol_admin_core_dialog_form:
    path:   /dialog-form    
    defaults: { _controller: ParabolAdminCoreBundle:Admin:dialogForm }

parabol_admin_core_setting:
    path:   /setting    
    defaults: { _controller: ParabolAdminCoreBundle:AppSetting:show }

# parabol_admin_core_file:
#     resource: "@ParabolAdminCoreBundle/Controller/File/"
#     type:     admingenerator
#     prefix:   /files


parabol_admin_core_dashboard:
    path:     /
    defaults: { _controller: ParabolAdminCoreBundle:Dashboard:index }

# parabol_admin_core_dashboard_widget_data:
#     path:     /dashboard/{widget}/data
#     defaults: { _controller: ParabolAdminCoreBundle:Dashboard:data }
